#!/usr/bin/env bash
set -euo pipefail
LIDAR_DEV="${1:-/dev/ttyUSB0}"
ARDUINO_DEV="${2:-/dev/ttyUSB1}"
RULE_FILE=/etc/udev/rules.d/99-mdetect-robot.rules

for dev in "$LIDAR_DEV" "$ARDUINO_DEV"; do
  [[ -c "$dev" ]] || { echo "Missing serial device: $dev" >&2; exit 1; }
done
[[ "$(readlink -f "$LIDAR_DEV")" != "$(readlink -f "$ARDUINO_DEV")" ]] || {
  echo "LiDAR and Arduino resolve to the same device." >&2; exit 1;
}

make_rule() {
  local dev="$1" link="$2" props serial path vendor product match
  props="$(udevadm info --query=property --name="$dev")"
  serial="$(awk -F= '$1=="ID_SERIAL_SHORT"{print $2; exit}' <<<"$props")"
  path="$(awk -F= '$1=="ID_PATH_TAG"{print $2; exit}' <<<"$props")"
  vendor="$(awk -F= '$1=="ID_VENDOR_ID"{print $2; exit}' <<<"$props")"
  product="$(awk -F= '$1=="ID_MODEL_ID"{print $2; exit}' <<<"$props")"
  if [[ -n "$serial" ]]; then
    match="ENV{ID_SERIAL_SHORT}==\"$serial\""
  elif [[ -n "$path" ]]; then
    match="ENV{ID_PATH_TAG}==\"$path\""
  else
    echo "Cannot create a persistent rule for $dev (no serial or USB path)." >&2
    return 1
  fi
  [[ -n "$vendor" ]] && match="ENV{ID_VENDOR_ID}==\"$vendor\", $match"
  [[ -n "$product" ]] && match="ENV{ID_MODEL_ID}==\"$product\", $match"
  printf 'SUBSYSTEM=="tty", %s, SYMLINK+="%s", GROUP="dialout", MODE="0660"\n' "$match" "$link"
}

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
{
  echo '# Generated by mDetect ROS 2 setup.'
  echo '# Current mapping: LiDAR='$LIDAR_DEV', Arduino='$ARDUINO_DEV
  make_rule "$LIDAR_DEV" coin_d6
  make_rule "$ARDUINO_DEV" arduino_mdetect
} > "$TMP"
sudo install -m 0644 "$TMP" "$RULE_FILE"
sudo udevadm control --reload-rules
sudo udevadm trigger --subsystem-match=tty
sleep 1

echo "Installed $RULE_FILE"
ls -l /dev/coin_d6 /dev/arduino_mdetect 2>/dev/null || {
  echo "Reconnect both USB devices once if the links have not appeared yet."
}
